#!/usr/bin/env python3
"""Generate STG's paragon leader backgrounds — the two files that make STNH's
52 leader-background textures reachable:

  src/gfx/portraits/asset_selectors/paragon_backgrounds.txt   vanilla + STG rows
  src/interface/stg_paragon_backgrounds.gfx                   the sprites

STNH's own selector is excluded in vendor.yml and stays excluded. It gates every
row on `is_earth_or_ufp_story_empire` / `uses_command_background` / `is_army_leader`,
which decision 16 left INERT on purpose, and on eight STNH country flags — so
unexcluding it would reach nothing while dropping vanilla's four legendary
paragon rows. STG re-gates on species class instead, exactly as decision 16 did
for clothing. Reasoning: .docs/decisions/50-paragon-backgrounds.md

Run from the repo root. Idempotent. Reads /stellaris and .source/.
"""
import re
import sys
from pathlib import Path

VANILLA = Path("/stellaris/gfx/portraits/asset_selectors/paragon_backgrounds.txt")
STNH = Path(".source/688086068")
SEL_OUT = Path("src/gfx/portraits/asset_selectors/paragon_backgrounds.txt")
GFX_OUT = Path("src/interface/stg_paragon_backgrounds.gfx")

# Selector rows, per species class. `commander` / `scientist` / `official` are
# three of vanilla 4.4's four leader classes (the fourth, `envoy`, has no
# paragon portrait); `ruler` is the selector's own second scope.
#
# STNH's `general_*` art has no row anywhere here, and that is not an omission:
# 4.x folded the army general into `commander`, so there is no leader class left
# to gate on. Its `*_earth_bg` pair has none either — STG has no United Earth,
# only the Federation it became.
#
# The era is TNG/DS9 throughout, as everything else in STG is (decision 16), so
# the Federation takes the `_tng_` cut of its eight and the other seven are
# untouched.
ROWS = [
    # class, commander,                      scientist,                       official,                    ruler
    ("FED", "admiral_federation_tng",  "scientist_federation_tng", "governor_federation",   "ruler_federation"),
    ("KDF", "admiral_klingon",         "scientist_klingon",        "governor_klingon",      None),
    ("ROM", "admiral_romulan",         "scientist_romulan",        "governor_romulan",      None),
    ("CAR", "admiral_cardassian",      "scientist_cardassian",     "governor_cardassian",   None),
    ("DOM", "admiral_dominion",        "scientist_dominion",       "governor_dominion",     None),
    # STNH ships no leader_scientist_ferengi_bg.dds and points its own
    # scientist sprite at the admiral texture; this does the same.
    ("FER", "admiral_ferengi",         "admiral_ferengi",          "governor_ferengi",      "governor_ferengi"),
    # One plate for every Borg role. STNH ships exactly one and so do we.
    ("BRG", "all_borg",                "all_borg",                 "all_borg",              "all_borg"),
    # The mirror Terran Empire and the Confederation of Earth get the two
    # plates STNH cut for them; neither has command or science art.
    ("TER", None,                      None,                       "governor_terran",       "ruler_terran"),
    ("CON", None,                      None,                       "governor_confederation", "ruler_confederation"),
]

SCOPES = ("commander", "scientist", "official", "ruler")
TEXDIR = "gfx/portraits/leaders"

HEADER_SEL = """\
# Star Trek Galaxies -- paragon leader backgrounds.
#
# SHADOWS gfx/portraits/asset_selectors/paragon_backgrounds.txt. Vanilla 4.4
# verbatim -- its four legendary rows included -- plus {n} STG rows that reach
# STNH's leader-background art by species class and leader class.
#
# STNH's own copy of this file stays excluded in vendor.yml: every row in it is
# gated on a trigger decision 16 left inert or on a country flag STG never sets,
# so it would reach nothing while dropping vanilla's four.
#
# GENERATED by tools/gen_paragon_backgrounds.py -- edit that, not this.
# See .docs/decisions/50-paragon-backgrounds.md
"""

HEADER_GFX = """\
# Star Trek Galaxies -- sprites for the paragon leader backgrounds.
#
# A NEW file, not a shadow: STNH declares these in interface/, which .docs/architecture/stnh-art.md
# does not take from it. The selector names `X`, the engine looks up
# `GFX_leader_X`, and the texture is STNH's under {texdir}/.
# The `stg_` prefix is ours because these selector keys are ours -- no vendored
# art references them, so decision 10's exception does not apply.
#
# GENERATED by tools/gen_paragon_backgrounds.py -- edit that, not this.
# See .docs/decisions/50-paragon-backgrounds.md
"""


def die(msg):
    sys.exit(f"gen_paragon_backgrounds: {msg}")


def close_of(text, at):
    depth = 1
    while depth:
        depth += (text[at] == "{") - (text[at] == "}")
        at += 1
    return at - 1


def main():
    if not (STNH / TEXDIR).is_dir():
        die(f"{STNH / TEXDIR} missing -- run `make sources-sync ID=688086068`")

    sprites: dict[str, str] = {}          # selector key -> texture basename
    rows: list[tuple[str, str, str]] = []  # scope, key, species class
    for cls, *arts in ROWS:
        for scope, art in zip(SCOPES, arts):
            if art is None:
                continue
            tex = f"leader_{art}_bg.dds"
            if not (STNH / TEXDIR / tex).is_file():
                die(f"{TEXDIR}/{tex} is not in the snapshot ({cls}/{scope})")
            key = f"stg_{cls.lower()}_{scope}_bg"
            sprites[key] = tex
            rows.append((scope, key, cls))

    # ── the selector: vanilla's file with our rows in front of its catch-all ──
    van = VANILLA.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
    out = van
    # The anchor is the FIRST catch-all in each scope, not the last row. A
    # selector takes the first entry whose trigger passes, and vanilla's
    # `bg_admiral = { leader_class = commander }` passes for every commander in
    # the game -- inserted below it, none of the Trek rows could ever fire.
    for scope_name, catch_all in (("leader", "bg_admiral"),
                                  ("ruler", "bg_ruler")):
        m = re.search(rf"^\t{scope_name} = \{{$", out, re.M)
        if not m:
            die(f"vanilla's file has no `{scope_name}` scope")
        end = close_of(out, m.end() + 1)
        body = out[m.end():end]
        # Ahead of the catch-all, behind vanilla's legendary rows: a legendary
        # leader is a specific named character and outranks a species look.
        anchor = re.search(rf"^\t\t{catch_all} = \{{$", body, re.M)
        if not anchor:
            die(f"vanilla's `{scope_name}` scope has no {catch_all} row")
        want = "ruler" if scope_name == "ruler" else None
        block = [f"\n\t\t# -- Star Trek. Species class is the gate, as it is for "
                 f"clothing (decision 16).\n"]
        for scope, key, cls in rows:
            if (scope == "ruler") != (want == "ruler"):
                continue
            cond = "" if scope in ("ruler",) else f"leader_class = {scope} "
            block.append(
                f"\t\t{key} = {{ {cond}exists = owner "
                f"owner = {{ owner_species = {{ is_species_class = {cls} }} }} }}\n")
        block.append("\n")
        at = m.end() + anchor.start()
        out = out[:at] + "".join(block) + out[at:]

    SEL_OUT.parent.mkdir(parents=True, exist_ok=True)
    SEL_OUT.write_text(HEADER_SEL.format(n=len(rows)) + out, encoding="utf-8")

    # ── the sprites ──────────────────────────────────────────────────────────
    lines = [HEADER_GFX.format(texdir=TEXDIR), "\nspriteTypes = {\n"]
    for key in sorted(sprites):
        lines.append(
            f'\tspriteType = {{ name = "GFX_leader_{key}" '
            f'texturefile = "{TEXDIR}/{sprites[key]}" '
            f'effectFile = "gfx/FX/buttonstate_onlydisable.shader" }}\n')
    lines.append("}\n")
    GFX_OUT.parent.mkdir(parents=True, exist_ok=True)
    GFX_OUT.write_text("".join(lines), encoding="utf-8")

    print(f"  {SEL_OUT}\n  {GFX_OUT}")
    print(f"    {len(rows)} selector row(s), {len(sprites)} sprite(s), "
          f"{len(set(sprites.values()))} of STNH's 52 textures reached")


if __name__ == "__main__":
    main()
