#!/usr/bin/env python3
"""Generate src/gfx/portraits/asset_selectors/room_textures.txt -- the one
room_selector STG ships.

Vanilla 4.4's file verbatim, plus STNH's Trek rooms re-gated on species class,
plus Diverse Rooms' designer list. STNH ships a 3.12 copy at vanilla's path
which drops 23 of vanilla's 42 designer rooms and 35 of its ruler rules, and
gates every Trek room on country flags STG never sets; Diverse Rooms ships a
SECOND file claiming `room_selector`, which is a coin toss nothing on disk
resolves. Reasoning: .docs/decisions/48-room-selector-merge.md

Run from the repo root. Idempotent. Reads /stellaris and .source/, never the
built tree -- src/ is applied last, so stg-build/ holds this script's own output.
"""
import re
import sys
from pathlib import Path

VANILLA = Path("/stellaris/gfx/portraits/asset_selectors/room_textures.txt")
STNH = Path(".source/688086068")
DIVERSE = Path(".source/3397828987")
OUT = Path("src/gfx/portraits/asset_selectors/room_textures.txt")

# ── which species class gets which Trek room, in the `ruler` scope ───────────
# Every row is STNH's own assignment, read off two of its files rather than
# chosen here: `gfx/portraits/asset_selectors/room_textures.txt` maps a room to
# an STNH country flag, and `prescripted_countries/STH_*.txt` maps that country
# to its `room =`. The species class is STG's join key, because the flags are
# the thing we do not vendor (decision 16).
#
# TRI is the one row not in STNH's prescripted files: they give the Trill
# Republic `personality_ruthless_capitalists_room`, but STNH's own selector maps
# its `trill_symbiosis_commission` country to `trillsym_room`, and STG's empire
# is the Symbiosis. THO has no row at all -- STNH gives the Tholian Assembly
# `personality_hive_mind_room` and ships no Tholian room; STG keeps the
# `lithoid_room` its LITHOID archetype asks for.
TREK_RULER_ROOMS = [
    ("FED", "earth_room", "UnitedEarth / tngUnitedFederationofPlanets"),
    ("VUL", "vulcan_room", "VulcanHighCommand, tngCoalitionHope"),
    ("KDF", "klingon_room", "KlingonEmpire"),
    ("ROM", "romulan_room", "RomulanStarEmpire"),
    ("CAR", "cardassian_room", "CardassianUnion"),
    ("BAJ", "bajoran_room", "BajoranRepublic"),
    ("FER", "ferengi_room", "FerengiAlliance"),
    ("TRI", "trillsym_room", "selector: trill_symbiosis_commission"),
    ("ADR", "andorian_room", "AndorianEmpire"),
    ("BOL", "bolian_room", "BolianLeague"),
    ("BET", "betazoid_room", "BetazoidHouses"),
    ("BRG", "borg_room", "BorgCollective"),
    ("DOM", "dominion_room", "TheDominion"),
    ("SUL", "suliban_room", "SulibanCabal"),
    ("XIN", "xindi_room", "XindiCouncil"),
    ("SHE", "sheliak_room", "SheliakCorporate"),
    ("VOT", "voth_room", "VothTheocracy"),
    ("UND", "undine_room", "UndineVanguard"),
    ("TER", "terran_room", "tngTerranEmpire"),
    ("VAU", "vaunakat_room", "VauNakatOrder"),
]

# Diverse Rooms entries whose trigger names an identifier no source in the
# harvest declares -- `ethic_light_side` and `ethic_dark_side` are a Star Wars
# mod's ethics. Same class as the UIOD speeddial re-skins vendor.yml excludes:
# an inert compat shim for a mod we do not ship. `civic_imperial_cult` IS
# vanilla, so imperium1/2 stay.
DIVERSE_SKIP = {
    "ethic_light_side_room", "ethic_light_side2_room",
    "ethic_dark_side_room", "ethic_dark_side2_room", "ethic_dark_side3_room",
}

HEADER = """\
# Star Trek Galaxies -- the room selector.
#
# SHADOWS gfx/portraits/asset_selectors/room_textures.txt, which STNH ships as
# its 3.12 copy of vanilla's file: 23 of vanilla's 42 designer rooms and 35 of
# its `ruler` rules are simply absent from it, and all 29 Trek rooms it names
# are gated on STNH country flags STG never sets -- so no Trek room was
# reachable and a third of vanilla's were not either.
#
# Vanilla 4.4 verbatim + STNH's {ntrek} Trek rooms + Diverse Rooms' designer list,
# whose own second `room_selector` is excluded in vendor.yml because two files
# claiming one selector name is decided by nothing on disk.
#
# GENERATED by tools/gen_room_selector.py -- edit that, not this.
# See .docs/decisions/48-room-selector-merge.md
"""


def die(msg):
    sys.exit(f"gen_room_selector: {msg}")


def close_of(text, at):
    """Index of the `}` closing the block whose `{` was just consumed at `at`."""
    depth = 1
    while depth:
        c = text[at]
        depth += (c == "{") - (c == "}")
        at += 1
    return at - 1


def trek_rooms():
    """Every *_room.dds STNH ships, read off the snapshot so the list cannot
    drift from the art."""
    d = STNH / "gfx/portraits/city_sets"
    if not d.is_dir():
        die(f"{d} missing -- run `make sources-sync ID=688086068`")
    return sorted(p.name[: -len(".dds")] for p in d.glob("*_room.dds"))


def diverse_game_setup():
    """Diverse Rooms' game_setup entries, verbatim, minus DIVERSE_SKIP."""
    f = DIVERSE / "gfx/portraits/asset_selectors/dr_room_textures.txt"
    if not f.is_file():
        die(f"{f} missing -- run `make sources-sync ID=3397828987`")
    t = f.read_text(errors="replace").replace("\r\n", "\n")
    block = t[t.index("game_setup"): t.index("ruler =")]
    out, seen = [], set()
    for m in re.finditer(
        r'"([a-z0-9_]+)"\s*=\s*(\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\})', block
    ):
        name, body = m.group(1), re.sub(r"\s+", " ", m.group(2)).strip()
        if name in DIVERSE_SKIP or name in seen:
            continue
        # `weight = { base = 10 }` is Diverse Rooms' own, and the engine reads
        # this block as a TRIGGER: `weight` is not one, so every row carrying it
        # logged two records -- 590 of the 2026-08-08 run's 2,020, its largest
        # class by far. Vanilla writes `weight` in 0 of its 160 asset_selector
        # game_setup scopes, so there is nothing here for it to mean.
        body = re.sub(r"\s*weight\s*=\s*\{[^{}]*\}", "", body)
        body = re.sub(r"\s+", " ", body)
        seen.add(name)
        out.append((name, body))
    if len(out) < 250:
        die(f"only parsed {len(out)} Diverse Rooms entries -- the file changed shape")
    return out


def main():
    van = VANILLA.read_text(encoding="utf-8-sig").replace("\r\n", "\n")
    trek = trek_rooms()
    diverse = diverse_game_setup()

    # Rooms with a ruler rule must be rooms that exist.
    for cls, room, _ in TREK_RULER_ROOMS:
        if room not in trek:
            die(f"{room} (class {cls}) is not a room STNH ships")

    # ── game_setup: append after vanilla's last entry ────────────────────────
    # Brace-matched rather than anchored on a room name: `nomads_science_room`
    # appears in both scopes, and an anchor that matches the wrong one would
    # put the Trek rooms in `ruler` with no trigger, where they are not a list
    # of offers but an unconditional override for every empire in the galaxy.
    end = close_of(van, van.index("game_setup = {") + len("game_setup = {"))
    end = van.rindex("\n", 0, end) + 1

    add = [
        "\n",
        "\t\t# -- Star Trek rooms (STNH art). Offered unconditionally, as every\n",
        "\t\t# vanilla entry above is: a game_setup entry is a room the designer\n",
        "\t\t# LISTS, and a prescripted empire's `room =` has to be in the list.\n",
    ]
    add += [f'\t\t"{r}" = {{ always = yes }}\n' for r in trek]
    add += [
        "\n",
        "\t\t# -- Diverse Rooms (Updated), from its own dr_room_textures.txt,\n",
        "\t\t# minus its `weight = { }` clauses: the engine reads this block as a\n",
        "\t\t# trigger and logged two records per row for them. See the note in\n",
        "\t\t# tools/gen_room_selector.py:diverse_game_setup().\n",
    ]
    add += [f'\t\t"{n}" = {b}\n' for n, b in diverse]
    van = van[:end] + "".join(add) + van[end:]

    # ── ruler: insert the Trek block ahead of vanilla's identity rules ───────
    # After the situational overrides (crisis, galactic emperor, marauder, the
    # origin- and flag-gated rooms) and before the portrait-family block, which
    # is the same kind of question the Trek rows ask.
    ins = '\t\t"lithoid_room" = {'
    if van.count(ins) != 1:
        die(f"expected exactly one {ins} in vanilla's ruler scope")
    at = van.index(ins)

    rows = [
        "\t\t# -- Star Trek identity. STNH gates these on its own country flags;\n",
        "\t\t# the species class is the join key STG has (decision 16). The\n",
        "\t\t# prescripted empires also carry the same room in `room =`.\n",
    ]
    for cls, room, why in TREK_RULER_ROOMS:
        rows.append(
            f'\t\t"{room}" = {{ exists = owner '
            f"owner = {{ owner_species = {{ is_species_class = {cls} }} }} }}"
            f"\t# {why}\n"
        )
    rows.append("\n")
    van = van[:at] + "".join(rows) + van[at:]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER.format(ntrek=len(trek)) + van, encoding="utf-8")
    print(f"  {OUT}")
    print(f"    vanilla base + {len(trek)} Trek room(s) + {len(diverse)} Diverse Rooms "
          f"entr(ies), {len(TREK_RULER_ROOMS)} ruler rule(s)")


if __name__ == "__main__":
    main()
