#!/usr/bin/env python3
"""Generate src/common/prescripted_flags/stg_empire_flags.txt — one country flag
per prescripted empire, set on the PLAYER's copy of it at country creation.

WHY THIS EXISTS. A static galaxy scenario pins an empire to a system with

    spawn_weight = { base = 0 modifier = { add = 100000 has_country_flag = X } }

and the home system's initializer creates the AI copy behind

    if = { limit = { NOT = { any_country = { has_country_flag = X } } } … }

Both halves are asking a question about a COUNTRY FLAG, and the player's own
empire has to be able to answer it. `common/prescripted_flags/` is where vanilla
puts that answer: `humans2` (the Commonwealth of Man) carries
`flag = empire_human_2`, and `00_default_empire_flags.txt` declares

    empire_human_2 = { flags = { human_2 custom_start_screen } }

so the player's CoM has `human_2` before a single system is generated. Vanilla's
`com_sol_system` then reads it during galaxy generation —

    usage_odds = { … modifier = { any_playable_country = { is_human_species = yes
                   OR = { has_country_flag = human_2 has_country_flag = human_3 } } … } }

— which is the on-disk proof that playable countries and their prescripted flags
exist BEFORE the initializers run. Without this file the guard can never see the
player, and picking the Klingons would put a second Klingon Empire on Qo'noS.

STNH does the same thing: `STNH_default_empire_flags.txt` gives its
`KlingonEmpire` design the `klingon_empire` flag its Qo'noS map entry and its
Qo'noS initializer both test. STG shipped neither half until now.

THE FLAG IS THE DESIGN KEY. `stg_klingon_empire` is the country flag, the
prescripted block key and the string all three sides join on, so there is one
name to get wrong rather than three. The prescripted_flags key is
`empire_` + the design key, which is vanilla's own convention.

`custom_start_screen` is deliberately NOT set: vanilla sets it on empires that
have a `common/start_screen_messages/` entry of their own, and STG has none.

The matching `flag = empire_<key>` line in `src/prescripted_countries/` is
hand-authored content, not generated — `check_prescripted_empires` asserts the
two sides agree.

See .docs/decisions/86-static-galaxy-scenario.md.

Run:  python3 tools/gen_empire_flags.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PRESCRIPTED = REPO / "src/prescripted_countries"
OUT = REPO / "src/common/prescripted_flags/stg_empire_flags.txt"

HEADER = """\
# GENERATED by tools/gen_empire_flags.py — do not hand-edit; regenerate.
#
# One entry per STG prescripted empire. The player's copy of an empire carries
# its design key as a country flag from the moment the country is created, which
# is what lets a static map's `spawn_weight` put the player on their own home
# system and what lets that system's initializer tell "nobody is playing this
# empire" from "the player is". Vanilla's own `empire_human_2` is the model.
#
# The flag IS the prescripted design key. Do not invent a second name for it.
#
# See .docs/decisions/86-static-galaxy-scenario.md.
"""


def empire_keys() -> list[str]:
    """Every `stg_*` prescripted design key, in file then declaration order."""
    keys: list[str] = []
    for path in sorted(PRESCRIPTED.glob("stg_*.txt")):
        text = path.read_text(encoding="utf-8-sig")
        keys += re.findall(r"^(stg_\w+) = \{", text, re.M)
    return keys


def main() -> int:
    keys = empire_keys()
    if not keys:
        print("no prescripted empires found — is the working directory the "
              "repo root?", file=sys.stderr)
        return 1

    dupes = {k for k in keys if keys.count(k) > 1}
    if dupes:
        print(f"duplicate design keys: {sorted(dupes)}", file=sys.stderr)
        return 1

    out = [HEADER]
    for key in keys:
        out.append(f"empire_{key} = {{\n\tflags = {{ {key} }}\n}}\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"{OUT.relative_to(REPO)}: {len(keys)} empire flags")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
